name: Run Ansible Playbook

on:
  schedule:
    - cron: "29 17 * * *"

jobs:
  run-playbook:
    if: github.ref == 'refs/heads/feature'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout feature branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Run playbook
        run: ansible-playbook playbook.yml
