name: Run Ansible Playbook

on:
  schedule:
    - cron: "15 53 * * *"

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Run playbook
        run: ansible-playbook playbook.yml
